<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.thatwhichis</groupId>
        <artifactId>htmx-qute-quarkus</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <name>boot</name>
    <artifactId>boot</artifactId>

    <dependencies>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>library</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>framework</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>core</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>app</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>jpa-adapter</artifactId>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>rest-adapter</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.dcadea</groupId>
            <artifactId>jresult</artifactId>
        </dependency>
        <!-- web dependencies -->
        <!--
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>htmx.org</artifactId>
            <version>2.0.1</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>htmx-ext-sse</artifactId>
            <version>2.2.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.mvnpm</groupId>
            <artifactId>htmx-ext-response-targets</artifactId>
            <version>2.0.0</version>
            <scope>provided</scope>
        </dependency>
        -->
        <!--        <dependency>-->
        <!--            <groupId>org.mvnpm</groupId>-->
        <!--            <artifactId>missing.css</artifactId>-->
        <!--            <version>1.1.2</version>-->
        <!--            <scope>provided</scope>-->
        <!--        </dependency>-->
        <!--        <dependency>-->
        <!--            <groupId>org.mvnpm</groupId>-->
        <!--            <artifactId>hyperscript.org</artifactId>-->
        <!--            <version>0.9.12</version>-->
        <!--            <scope>provided</scope>-->
        <!--        </dependency>-->
        <!-- AUTHENTICATION/AUTHORIZATION -->
    </dependencies>
</project>
