[language-server.jdtls]
command = "jdtls"
args = ["-data", "../.settings"]

[language-server.jdtls.config.settings]
"java.maven.downloadSources" = true
"java.import.maven.enabled" = true
"java.references.includeDecompiledSources" = true
"java.configuration.updateBuildConfiguration" = "interactive"

[[language]]
name = "java"
auto-format = true
scope = "source.java"
injection-regex = "java"
file-types = ["java"]
roots = ["pom.xml"]
language-servers = ["jdtls"]

[language.indent]
tab-width = 4
unit = "    "
