<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>dev.thatwhichis</groupId>
        <artifactId>htmx-qute-quarkus</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>e2e</artifactId>

    <properties>
        <maven.compiler.source>25</maven.compiler.source>
        <maven.compiler.target>25</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>boot</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>library</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>framework</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>app</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>jpa-adapter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>dev.thatwhichis</groupId>
            <artifactId>rest-adapter</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-security-oidc</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-vertx</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-test-hibernate-reactive-panache</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jacoco</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/test/resources</directory>
            </resource>
            <resource>
                <directory>../adapters/inbound/rest-adapter/src/main/resources</directory>
            </resource>
        </resources>

        <plugins>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>