# cors
quarkus.http.cors.enabled=true
# database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
# hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
# otel
quarkus.otel.enabled=${OTEL_ENABLED:false}
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.exporter.otlp.protocol=grpc
quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT}
quarkus.otel.exporter.otlp.headers=authorization=Bearer ${OTEL_TOKEN} 
# oidc
quarkus.oidc.enabled=true
quarkus.oidc.client-id=reactive-todos
quarkus.oidc.tls.verification=none
quarkus.oidc.devui.grant.type=password
quarkus.oidc.devui.grant-options.password.audience=http://localhost:8080
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web-app
quarkus.oidc.discovery-enabled=true
quarkus.oidc.logout.path=/logout
quarkus.oidc.logout.post-logout-path=/
# devservices
quarkus.devservices.enabled=true
quarkus.datasource.devservices.username=quarkus
quarkus.datasource.devservices.password=quarkus
quarkus.datasource.devservices.db-name=quarkus
quarkus.datasource.devservices.port=5432
quarkus.keycloak.devservices.enabled=true
# if otel is enabled, it is recommended to enable traces in the logs
# quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId} %n [%c{2.}] (%t) %n %s%e%n