# application
quarkus.application.name=reactive-todos
quarkus.application.version=1.0.0-SNAPSHOT
# log
quarkus.log.level=INFO
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId} %n [%c{2.}] (%t) %n %s%e%n