# database
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.jdbc.telemetry=true
quarkus.datasource.jdbc.telemetry.trace-connection=true
# hibernate
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
# oidc
quarkus.oidc.enabled=true
quarkus.oidc.client-id=reactive-todos
quarkus.oidc.tls.verification=none
quarkus.oidc.devui.grant.type=password
quarkus.oidc.devui.grant-options.password.audience=http://localhost:8080
quarkus.oidc.credentials.secret=secret
quarkus.oidc.application-type=web-app
# otel
quarkus.otel.enabled=${OTEL_ENABLED:false}
quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
quarkus.otel.exporter.otlp.protocol=grpc
quarkus.otel.exporter.otlp.endpoint=${OTEL_ENDPOINT}
quarkus.otel.exporter.otlp.headers=authorization=Bearer ${OTEL_TOKEN} 
# devservices
quarkus.devservices.enabled=true
quarkus.datasource.devservices.port=5432
quarkus.keycloak.devservices.enabled=true