name: Maven Build and Save Artifacts

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build:
    name: maven build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install java 23 [liberica-jdk]
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'liberica'
          cache: maven
      - name: Maven build
        run: ./mvnw clean package -Pmonolith