name: Maven Build and Save Artifacts

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build:
    name: maven build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          download_url="https://download.java.net/java/early_access/jdk24/28/GPL/openjdk-24-ea+28_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          distribution: 'jdkfile'
          architecture: x64
          cache: maven
      - name: mvn clean install
        run: ./mvnw clean install -Pmonolith -Dquarkus.profile=test