name: Maven Build and Save Artifacts

on:
  pull_request:
    branches:
      - 'feature/**'
      - 'bugfix/**'
      - 'hotfix/**'

jobs:
  build:
    name: maven build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'graalvm'
          cache: maven
      - name: mvn clean install
        run: ./mvnw clean install -Pmonolith -Dquarkus.profile=test