name: Maven Build and Save Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: compile, build, test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'zulu'
          cache: maven
      - name: mvn clean install
        run: ./mvnw clean install -Pmonolith -Dquarkus.profile=test
      - run: mvn --batch-mode --update-snapshots verify
      - uses: actions/upload-artifact@v4
        with:
          name: quarkus-app
          path: application/configuration/monolith-configuration/target/quarkus-app/

  push:
    name: build image, push to registry
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
        with:
          name: quarkus-app
          path: quarkus-app
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nanobreaker/reactive-todos-service:1.0.0-SNAPSHOT