name: Maven Build and Save Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven
      - name: Maven build
        run: ./mvnw clean install -Pmonolith
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir deployments
      - run: cp application/configuration/monolith-configuration/target/quarkus-app/lib/ deployments/lib
      - run: cp application/configuration/monolith-configuration/target/quarkus-app/*.jar deployments
      - run: cp application/configuration/monolith-configuration/target/quarkus-app/app/ deployments/app/
      - run: cp application/configuration/monolith-configuration/target/quarkus-app/quarkus/ deployments/quarkus/
      - uses: actions/upload-artifact@v3
        with:
          name: quarkus-artifacts
          path: deployments