name: Maven Build and Save Artifacts

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: maven build and upload artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'liberica'
          cache: maven
      - name: Maven build
        run: ./mvnw clean install -Pmonolith
      - run: mvn --batch-mode --update-snapshots verify
      - run: mkdir deployments
      - run: cp -r application/configuration/monolith-configuration/target/quarkus-app/lib/ deployments/lib
      - run: cp application/configuration/monolith-configuration/target/quarkus-app/*.jar deployments
      - run: cp -r application/configuration/monolith-configuration/target/quarkus-app/app/ deployments/app/
      - run: cp -r application/configuration/monolith-configuration/target/quarkus-app/quarkus/ deployments/quarkus/
      - uses: actions/upload-artifact@v3
        with:
          name: quarkus-artifacts
          path: deployments

  push:
    name: docker build and push image
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: nanobreaker/reactive-todos-service:1.0.0-SNAPSHOT